#! /bin/sh

set -e

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

rm -rf autom4te.cache
$AUTORECONF -v -f -i

patch -p0 <build-aux/config.sub.patch

echo "Reconfiguration done."
