SIM_SOURCES = \
	sim/breakpoints.cpp \
	sim/breakpoints.h \
        sim/configmap.cpp \
        sim/configmap.h \
        sim/configparser.cpp \
        sim/configparser.h \
	sim/config.cpp \
	sim/config.h \
        sim/convertval.cpp \
        sim/convertval.h \
        sim/ctz.h \
	sim/delegate.h \
	sim/except.h \
	sim/except.cpp \
        sim/inputconfig.h \
        sim/inputconfig.cpp \
	sim/inspect.h \
	sim/inspect.cpp \
	sim/kernel.h \
	sim/kernel.cpp \
	sim/log2.h \
        sim/modelregistry.h \
        sim/modelregistry.cpp \
	sim/monitor.h \
	sim/monitor.cpp \
	sim/ports.h \
	sim/ports.cpp \
	sim/range.h \
        sim/readfile.h \
        sim/readfile.cpp \
        sim/rusage.h \
        sim/rusage.cpp \
	sim/sampling.h \
	sim/sampling.cpp \
	sim/storage.h \
	sim/storagetrace.h \
        sim/storagetrace.cpp \
	sim/types.h \
        sim/unreachable.h
 


