#!/bin/bash
#
# Script that generates a list of hosts that are live at the moment.
#

function check_host
{
    host=$1

    # Check if the host is alive
    ping -q -W 1 -c 1 $host &> /dev/null || return
    
    # Start remote job
    # Connects to host, and checks if all libraries are present
    # If so, prints hostname
    rsh $host '! ldd ~/MGSim/MGSim | fgrep -q "not found" && hostname' &
    export CHILD=$!
    
    # Set abortion trap
    trap 'kill $CHILD' EXIT
    
    # Start timer subshell
    (usleep 500000; kill $CHILD &>/dev/null)&
    TPID=$!
    
    # Wait for the remote job to exit
    wait $CHILD &>/dev/null
    
    # Kill timer
    kill $TPID &>/dev/null
    wait $TPID &>/dev/null
}

for i in `seq 1 200`
do
    host="ow$i"
    check_host $host
done

for i in `seq 1 100`
do
    host=`printf 'owf-%02d' $i`
    check_host $host
done
