DEMO_SRC = \
	demo/tinysim.h \
	demo/tinysim.cpp \
	demo/memclient.h \
	demo/memclient.cpp \
	demo/prodcons2.h \
	demo/prodcons2.cpp \
	demo/prodcons.h \
	demo/prodcons.cpp \
	demo/example.cpp

DEMO_SOURCES = $(DEMO_SRC)

